<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>openverse-decker</AssemblyName>
    <RootNamespace>OpenVerse.Decker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenVerse.Common\OpenVerse.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\unlimited_cards.json" />
    <EmbeddedResource Include="Resources\resurgent_cards.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
</Project>
